// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkQbjVP0BHZRkvjvReei41hjCNZ9UrOBA',
    appId: '1:462632915382:web:0d294ca77060879380f117',
    messagingSenderId: '462632915382',
    projectId: 'mad-lab-f4f2c',
    authDomain: 'mad-lab-f4f2c.firebaseapp.com',
    storageBucket: 'mad-lab-f4f2c.firebasestorage.app',
    measurementId: 'G-Z43XK5MZ30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkohdVY9NYGCITky9TVBMCiUD8dg3GqwQ',
    appId: '1:462632915382:android:521097160a823eda80f117',
    messagingSenderId: '462632915382',
    projectId: 'mad-lab-f4f2c',
    storageBucket: 'mad-lab-f4f2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPwE2LL-Ccl88jvfxcv82ZJDIoRVpCM-I',
    appId: '1:462632915382:ios:fa5852973ac1dc6780f117',
    messagingSenderId: '462632915382',
    projectId: 'mad-lab-f4f2c',
    storageBucket: 'mad-lab-f4f2c.firebasestorage.app',
    iosBundleId: 'com.example.mplLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPwE2LL-Ccl88jvfxcv82ZJDIoRVpCM-I',
    appId: '1:462632915382:ios:fa5852973ac1dc6780f117',
    messagingSenderId: '462632915382',
    projectId: 'mad-lab-f4f2c',
    storageBucket: 'mad-lab-f4f2c.firebasestorage.app',
    iosBundleId: 'com.example.mplLab',
  );
}
